### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MaxOstrowski** [VictosVertex/asp-lsp#2]
I think/hope that I use your language server in VSCode, but it recently crashed during a video session.
I can not share the whole log as it contains proprietary code, but maybe this error message already helps to find a bug:

```
thread 'main' panicked at src/semantics/statement_semantic.rs:1174:44:
called `Option::unwrap()` on a `None` value
```

I think this happened while simply writing random text inside an already existing ASP encoding as we have been brainstorming and were scribbling around.

**Comment by VictosVertex** [comment]
Hey, yes this is indeed the right language server. Some of the older code sadly uses `unwrap()` in not so secure places. I'll take a look at it!

**Comment by VictosVertex** [comment]
This should be fixed now, there basically was an index error when dealing with `optconditions` inside `disjuctions`.
